### ISSUE TITLE
Trezor AQUA claim work around no longer working around ;-(

### ISSUE THREAD

**Issue by FastlaneSchweiz** [vinamogit/trezor-workaround#3]
Hi Vincent I am very grateful for your work around. Unfortunately its stopped working it hangs at the waiting for wallet stage when signing the first submission..

Generate XDR, enter XDR, sign - waiting for wallet. Indefinitely. If you need screenshots happy to provide.

**Comment by vinamogit** [comment]
Hi,
This is a known issue with trezor-connect and the latest stellar sdk.
The fixes have been pushed on trezor side, it looks like it's almost ready to be published.
After that the stellar laboratory will be updated and then you will be able to sign with the lab.

In the meantime, if you have other ways to sign your transactions this should work.

For reference, here is the trezor PR that should solve the issue (i.e. contains the fix):
https://github.com/trezor/trezor-suite/pull/9755

**Comment by felixlucid** [comment]
Thank you so much for all you do Vinamogit! If it wasn't for you, I would have never been able to claim a single airdrop. Unfortunately, the stellar lab hasn't been working for months now. When I try to sign the transaction, I get the error: "Invalid parameter "signer/key" (= undefined): Expected union value" and sadly, the stellar lab still doesn't seem to have resolved the Trezor issue. Could you please check to see if maybe the problem is on my end, or do you also experience the same error? Thank you so much for your attention.

**Comment by vinamogit** [comment]
Hi,
This workaround should be deprecated now since Trezor added the ability to claim claimable balances directly.
If you want to claim some Aqua airdrop you should go to aqua.network and use the "stellar laboratory" login type and follow the procedure.
I hope this should work now.

**Comment by bjorn** [comment]
> This workaround should be deprecated now since Trezor added the ability to claim claimable balances directly.

Hmm, at least with my Trezor One this still doesn't work since it locks up when trying to sign the claim transaction from aqua.network/account, like it always used to do when trying to sign claiming transactions. Trezor Suite shows it has the [latest firmware](https://github.com/trezor/trezor-firmware/blob/main/legacy/firmware/CHANGELOG.md) installed (which is 1.12.1 from 15th March 2023, so it obviously will not contain any recent bugfix).

I'm currently running into the same issue as @felixlucid. Might need to find some other way to sign then, or try with a Trezor Model T.
